const HTTP_STATUS_CODE = {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    CONFLICT: 409,
    UNAUTHORIZED: 401,
    SERVICE_UNAVAILABLE: 503,
};
const Role = {
    ADMIN: 'admin',
    USER: 'user',
};
const FOLDER_CLOUD_AVATARS = 'avatars'

module.exports = { HTTP_STATUS_CODE, Role, FOLDER_CLOUD_AVATARS};